docs/index.restdown

Fix typeo for CORS docs

---

README.md

SVG badges in README

---

docs/index.restdown

Change it to res.body since body is undefined.

fix issue #701

---

lib/formatters/jsonp.js
test/client.test.js

A resubmission of #729 using the latest version of Restify. Includes unit test.

Added typeof check to JSONP callback

---

test/client.test.js

Late testing for issue #686 requested in pull request #800

Testing for issue #686 (Allow 0, false, and null as json body) #800

---

docs/index.restdown
lib/plugins/audit.js
test/plugins.test.js

add req.query to auditlogger

---

package.json

Fix for #830
Also see https://github.com/chrisa/node-dtrace-provider/pull/61

dtrace-provider version bump

---

docs/index.restdown
lib/server.js
test/server.test.js

Fixed up the PR #630 from @OiNutter to include:
* Tests
* Updated Docs
* Formatting for jscs

Fix issue with Server toString method 

---

lib/response.js
test/formatter.test.js

Reverts restify/node-restify#839

Revert "Send 500 status if async formatter sends error"

---

docs/index.restdown
lib/request.js
lib/router.js
test/server.test.js

Fix up JSCS errors from #635 by @nathanpeck

Adding req.matchedVersion()

---

docs/index.restdown

clarify that certain req properties are functions.

---

examples/dtrace/demo.js

There were some inconsistencies in the DTrace demo.

Correct examples/dtrace/demo to use cb formatter

---

README.md

Markdown doesn't center :(  unless we can make svg scale to max width? My markdown fu is no bueno.

add logo to readme

---

.eslintrc
package.json

Update dependencies:
Dep | Old Version | New Version
-------- | --------- | -----------
qs | ^3.1.0 | ^5.0.0
semver | ^4.3.3 | ^5.0.1
Dep | Old Version | New Version
-------- | --------- | -----------
eslint | ^0.24.0 | ^1.3.1
jscs | ^1.13.1 | ^2.1.1

Update several dependencies to latest

---

CHANGES.md

Mark formatter api change as breaking

---

package.json

Fix https://github.com/restify/node-restify/issues/931#issuecomment-146325503

package: update spdy to 2.0.5

---

docs/branding/footer.html.in
docs/branding/header.html.in
tools/mk/Makefile.targ

Add the github button to the branding header template file and add the arguments to the restdown call
Closes #926

Use custom branding in order to add the github button

---

docs/index.restdown
lib/server.js
test/server.test.js

@yunong @micahr rebased onto 5.x branch.

GH-667: support generic error listener

---

docs/index.restdown

updated docs to provide a working example

made socket.io sample working - listen() server.server

---

lib/router.js
test/server.test.js

GH-959: fixes issue where cached routes were not setting maxVersion on req

---

examples/todoapp/lib/server.js
examples/todoapp/package.json

Make the Todo App work again with the new Restify Errors signatures and async formatters
Fixes #975

Fix todoapp example by using latest restify-errors

---

lib/response.js
package.json
test/server.test.js

Fixes https://github.com/restify/node-restify/issues/986

Content-Type should not contain multi-values. Closes #986

---

lib/router.js
test/router.test.js

fix potential xss vector

---

.eslintrc
package.json
test/formatter.test.js

Not sure why greenekeeper's PRs have a million commits in them. Hopefully this will make it work again.

update eslint to 2.x

---

package.json

rev node-uuid to fix nsp advisory CVE-2015-8851

---

lib/server.js
test/server.test.js

GH-999: normalize NotFound error handler to flush response

---

lib/router.js
test/server.test.js

This is an update on a previous PR with all the latest updates from 5.x. This time tests pass.

Removing route from LRU cache on unmount.

---

lib/formatters/binary.js
lib/formatters/json.js
lib/formatters/jsonp.js
lib/formatters/text.js
lib/response.js
lib/server.js
test/formatter.test.js
test/server.test.js

Attempts to fix #845, but there are some gaps. Conversation will continue in that thread.

GH-845: support both sync and async formatters

---

lib/server.js

GH-1119: when req.clientClosed is true, set res statusCode to 0

---

lib/index.js
lib/server.js
test/server.test.js

GH-1078: send server name property down as header

---

lib/deprecationWarnings.js
lib/server.js
test/server.test.js

GH-1123: add deprecation warnings for domain dependent features

---

lib/response.js
test/server.test.js

GH-1128: don't serialize and send domain errors to client

---

4TO5GUIDE.md
CHANGES.md
docs/pages/components/plugins.md
docs/pages/components/request.md
docs/pages/components/response.md
docs/pages/components/server.md
docs/pages/guides/getting-started.md
docs/pages/guides/server.md
lib/request.js

update changes.md, add migration guide

---

docs/pages/components/plugins.md

Added some docs about a new optional serveStatic option. 
For more details, see [this pull request](https://github.com/restify/plugins/pull/41)

Add some docs about the serveStatic plugin (appendRequestPath option)

---

lib/router.js
test/server.test.js

Updated Router unmount() to check if there are other versions for a certain route to fix https://github.com/restify/node-restify/issues/1171
First open-source contribution here ever.. so hope I'm doing it right.
I used the existing Router findByPath method instead of an O(n) filter()
Cheers,
Georges

Update Router unmount to check if other versions exist

---

package.json

rev formidable to remove Node6+ warnings

---

.travis.yml
package.json

Also update some greenkeeper deps.

Remove 0.10 and 0.12 travis support

---

docs/pages/components/request.md
docs/pages/components/server.md
lib/request.js
lib/server.js
test/request.test.js
test/server.test.js

allow request id to be set. remove reqIdHeaders option

---

CHANGES.md
docs/pages/components/server.md
lib/server.js
test/server.test.js

Emit 'pre' and 'routed' events

---

lib/bunyan_helper.js
lib/request.js
lib/server.js
package.json
test/client.test.js
test/server.test.js

This was fixed in 5.x, but since we haven't been able to get it out of beta yet, doing in on 4.x too.

Upgrade: update uuid

---

README.md
docs/pages/index.md

Removing references to IRC

---

index.html

Fix documentation for conditionalRequest

---

lib/server.js

Fixes #1278
Leaves tests to verify the behaviour the original PR was meant to introduce.

Removing duplicate close event

---

docs/guides/client.md

Fix to .createJsonClient is not a function error. Updated the code samples.
Closes:
* Issue #1188
* Issue #
* Issue #
Updates the code samples of the client.md documentation.

Updated Client Guide

---

docs/api/server.md

Closes:
#1446 
Documentation updates.

docs: update docs on emitted error event strings

---

README.md

Closes:
* Issue #
* Issue #
* Issue #

chore(readme): minor style fix for code example

---

package.json

Moving #1444 from v5 to master

BREAKING CHANGE: bump restify-errors version to v5

---

docs/api/server.md
docs/guides/server.md

This restores the server guide from the old restify.com. Also addresses #1459

Chore: restore server guide from old restify.com

---

docs/api/request.md
package-lock.json

- Fix a typo in the API docs `request.path()` code snippet

docs(api): fix code snippet for path

---

lib/plugins/cpuUsageThrottle.js

Closes:
* Issue #
* Issue #
* Issue #

fix(cpuUsageThrottle): Always queue a new timeout

---

examples/sockio/package.json
examples/sockio/sockio.js

Fix socket.io example.
- fix example
- add `package.json` to the sockio example

Fix socket.io example

---

docs/api/plugins.md
lib/plugins/audit.js
package-lock.json
test/plugins/audit.test.js

Add a context option to the audit logger plugin to support arbitrary user added context to the audit log payload.

new: audit logger plugin now supports custom context objects

---

package-lock.json

Reference: #1524
Removes `artifacts.netflix.com` from package-lock.json

fix(package-lock.json): remove artifacts.netflix.com repo

---

docs/_api/server.md
docs/api/server-errors.md
docs/api/server-events.md
lib/server.js

- Fix JSDoc optional callbacks parameters
- Fix JSDoc for "array of" parameters
- Add more examples to JSDoc
- Improve `server-errors` and `server-events` docs
- Generate server docs

Improve server docs

---

benchmark/index.js

- Improve grammar
- Print stable version

chore(benchmark): improve grammer

---

lib/plugins/audit.js

Just a little fix in the documentation ;)

docs(audit): fix the example to add event option

---

package.json

Update dependencies: `mime`
- update `mime` to `1.5`
- update dev dependencies

Update dependency: mime

---

docs/_api/server.md

- This is a simple documentation change. If an issue to discuss these changes is deemed necessary still, I will do that.
- Just docs changes, no test changes or linting required.
There are no open issues regarding these changes.
Fixed what looked like some copy-pasta in server creation examples.

Minor typo corrections in examples.

---

docs/_api/plugins.md

Closes:
* None
*Documentation Fix*: Correct invalid regular expression for serveStatic example which was missing a closing `/`

staticServer doc fix

---

lib/plugins/multipartBodyParser.js
test/plugins/multipart.test.js

Closes:
* Issue #1620
> Passes maxFileSize option provided to restify.plugins.bodyParser() down into formidable.
> Adds test for maxFileSize enforcement to multipart testing.

Pass max file size to formidable

---

lib/plugins/accept.js
test/plugins/accept.test.js

fix: server should fire not acceptable event

---

package.json

Closes:
* Issue #1650 
autocannon@0.16.5 won't work on Node.js v10.0.0 because one dependency
is broken. Updating to autocannon@2.2.0 fix node-restify installation on
Node.js 10.
This PR updates autocannon to v2.2.0 to fix installation on Node.js 10

chore(package): update autocannon version

---

package.json

Closes:
* Issue #1654 
Upgrade tunnel-agent to 0.6.0. The previous version (0.4.3) was being reported by nsp as having a vulnerability, which was addressed in 0.6.0.

FIX : update tunnel-agent to 0.6.0

---

.npmignore
package.json

Closes:
* Issue #
* Issue #
* Issue #
Corrects the homepage link (shows up incorrectly on npmjs) and adds IDE specific folder to `.npmignore` which ensures developers dont publish those files when running `npm publish`

chore(dev): fix homepage info and npmignore

---

package.json

chore: update engines field in package.json

---

lib/plugins/audit.js
package.json

- Update restify-errors to 8
- remove unnecessary verror dependency

chore(package): use restify-errors 8.x

---

.npmignore

fix(npm): exclude extraneous files

---

package.json

chore(deps): upgrade mocha

---

test/plugins/gzip.test.js

the last merge to master broke the build. These PR builds had succeeded a long time ago...

tests(ci): fix build

---

lib/plugins/audit.js
lib/plugins/requestLogger.js

Closes:
* Issue #
* Issue #
* Issue #

chore!: remove deprecated usage of pino.child

---

.github/workflows/release-please.yml

Closes:
* Issue #
* Issue #
* Issue #

chore: 9.x release-please

---

lib/request.js

Closes:
* Issue #
* Issue #
* Issue #

feat: emit warning for req.closed only once

---

package.json
test/router.test.js
test/routerRegistryRadix.test.js

This fixes tests related to a recent `find-my-way` release. The relevant change is: https://github.com/delvedor/find-my-way/pull/321

fix: tests broke due to find-my-way update
