restify/node-restify

- docs/index.restdown
- lib/server.js
- test/server.test.js
This is especially helpful for server 5XX or 4XX error pages. You can listen for say, `InternalServerError`, and then decorate that error with information globally, without having to do that every time the error is served.
> Add ability to listen for error events

- lib/plugins/json_body_parser.js
- test/plugins.test.js
With req.body === 'null', we have an error : Object.keys called on non-object.
Thanks to some investigations we found that params is null and in Javascript typeof null === 'object'.
> Fix a bug when req.body === 'null'

- lib/clients/http_client.js
- test/client.test.js
Allow override of agent option to ```false``` for each request. 
Currently you can override an agent to true, or to an Agent object, but overriding to ```false``` will shortcut (via ```||```) to whatever the global setting is (```true```, ```false```, ```Agent```, or even ```undefined```).
In short, this pull request will make a per request ```false``` setting override the global setting.
> Enable {agent: false} option override per request

- lib/request.js
- test/server.test.js
When `req.path()` was [made into a function](https://github.com/mcavage/node-restify/wiki/1.4-to-2.0-Migration-Tips#reqpath---reqpath-or-reqgetpath), `req.absoluteUri(path)` wasn't updated to invoke it. Currently, it serializes the JavaScript implementation of `req.path()` if the `path` argument to `req.absoluteUri(path)` doesn't include a path component (e.g. it's a query or a fragment).
e.g.
```
Link: <http://localhost/:8000function%20getPath()%20{%0A%20%20%20%20%20%20%20%20if%20(this._path%20!==%20undefined)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20(this._path);%0A%0A%20%20%20%20%20%20%20%20this._path%20=%20this.getUrl().pathname;%0A%20%20%20%20%20%20%20%20return%20(this._path);%0A}/?after=502b0dee92169e6654000074>; rel="next"
```
> add missing fn invocation in req.absoluteUri

- lib/plugins/fielded_text_body_parser.js
- test/fieldedTextParser.test.js
Body parser expects this function to return a handler function, rather than an array of handlers.  Currently, requests with `Content-Type: text/csv` will crash the server unless there is a handler for uncaught exceptions.
> Fix issue #691

- lib/plugins/audit.js
This allows an app to have a custom err serializer (e.g.
one that adds extra fields from the error object) and
have the audit logs use it.
> Prefer the existing 'err' serializer for audit logging

- lib/index.js
According to the documentation http://nodejs.org/api/http.html#http_response_headerssent, we can use `headersSent`.
I may be wrong on this one, but this just bit us in production where we had a custom `server.on('uncaughtException')` listener, and the `res._headerSent` were not working. Updating this to `headersSent` fixed the problem.
It looks to be available under node 0.10 only, if we want to maintain compatibility maybe we should use `|| res._headerSent || res.headersSent`.
I can't find any reference in the code where you set the `_headerSent` value, so I figured you were using a deprecated value from a low-level library.
> Replace _headerSent with headersSent

- lib/router.js
- test/server.test.js
Route names appear to be normalised when they're added to the router but during route chaining the route name requested is used for the lookup verbatim.
This has the upshot that it is non-obvious how to chain to a route named `'test-route'`.
> Normalise route names when chaining routes

- lib/server.js
When I updated to the latest restify I got the following error all of a sudden:
Error: Can't set headers after they are sent.
at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
...
I can get around the problem by not having socket.io use the restify server instance and listen on its own port instead of sharing it.
So normally I'd use:
server = restify.createServer()
socketServer = io.listen( server )
server.listen( 8080 )
Fixing requires either sticking with 2.8.1 or choosing a different port/listener for socket.io:
server = restify.createServer()
socketServer = io.listen( 8081 )
server.listen( 8080 )
All this worked flawless before the minor update. I'm trying to figure out if this is an issue with socket.io , restify or something in how my code uses either. Since the minor …
> upgrade restify 2.8.1 to 2.8.2 breaks socket.io 1.x integration

- docs/index.restdown
The naming of the requestLogger plugin is slightly misleading.
> Improve RequestLogger documentation

- docs/index.restdown
Server API event listener examples were missing error param, causing cb to be in wrong position. I believe the docs became outdated on commit ab1a7522af51a4337468f06cf4b929b05fba458f
> Update index.restdown for Server API error event listener examples

- lib/router.js
- lib/server.js
I was pulling `compileURL` out of *lib/router.js* into a separate module and noticed that *lib/router.js* had variables declared that weren't ever used. Upon further inspection, I found this to be the case in *lib/server.js* as well. 
Unused variables make code harder to read. They create an inaccurate overview of the file at hand.
I've:
* Removed the unused variables in *lib/router.js*
* Removed the unused variables in *lib/server.js*
* Rectified the stylistic discrepancies on line 254 of *lib/server.js* that were causing tests to fail on Node.js v0.12.2 (`make: *** [lib/server.js.jsstylechk] Error 1`)
> Rectify jsstylechk errors, remove unused vars in server+router

- lib/router.js
- test/router.test.js
Hi,
I was trying to use the Hypermedia API to render all the internal links in my API, when suddenly some of the paths was rendered wrongly - the latter parameters was simply left out of the rendered path.
So if I had a path like
/:param1([0-9]+)/:param2([0-9]+)
Then when I did a render with `param1` to 1, and `param2` to 2, the rendered path was only `/1`, and not `/1/2` as expected.
I tracked the problem down to how the different params are identified using a regular expression. The pattern was too greedy, so faced with two sets of parameters, it would simply match all the way from the start of the first to the end of the latter parenthesis. So the regex would have the following captures
match #     group 0                              group 1      group 2
1 …
> Hypermedia API fails when paths have multiple patterns with sub-regexs

- lib/response.js
0, false, and null are all valid body contents of a request, however currently only an empty body is returned in these cases.
For Example:
response.json(200, true);
- currently returns:
200 OK
true
- however false doesn't return a body:
response.json(200, false);
200 OK
Change allows false to also return:
response.json(200, false);
200 OK
false
> Allow 0, false, and null as json body #686

- README.md
- docs/branding/header.html.in
- docs/index.restdown
- examples/todoapp/package.json
- package.json
- Update links from github.com/mcavage/node-restify/ to
github.com/restify/node-restify
- Update links for mcavage.github.com to restifyjs.com
> Update all links to the new github organization location

- .npmignore
E.g. in restify@3.0.3 these are:
$ du -sh ...
1.3M cover_html
1.8M .coverage_data
Details:
```
$ npm install restify@3.0.3
...
$ du -sh * .??*
16K	CHANGES.md
4.0K	LICENSE
4.0K	README.md
8.0K	bin
1.3M	cover_html
268K	lib
4.0M	node_modules
8.0K	package.json
1.8M	.coverage_data
4.0K	.npmignore
```
> don't include (large) coverage files in published packages

- docs/index.restdown
- lib/request.js
- test/plugins.test.js
- test/request.test.js
Fixes #374, but also changes the default behavior of req.getQuery(). There was some blurring of behavior between the default behavior, and the behavior expected from using the queryParser plugin.
Previously, if you were not using the queryParser plugin, you'd get an empty object, which is consistent with behavior from the queryParser plugin, but __inconsistent__ with the behavior of req.getQuery().
```
/foo 
req.getQuery(); // => {}
req.query; // => {}
/foo?a=1
req.getQuery(); // => 'a=1'
req.query; // => {a: 1}
```
With this pull request, the behavior is now:
```
/foo 
req.getQuery(); // => ''
req.query; // => {}
```
If you're using the plugin, you'll always get objects returned using `req.query`, but now `req.getQuery()` will consistently return a string even if you don't use the …
> req.getQuery() always returns a string

- lib/clients/http_client.js
- test/client.test.js
The policy is similar to what [request](https://github.com/request/request#proxies) uses.
no_proxy should contain a comma separated list of hosts to opt out of proxying.
It is also possible to opt of proxying when a particular destination port is used.
Finally, the variable may be set to * to opt out of the implicit proxy configuration of the other environment variables.
> Consider no_proxy env variable while setting proxy for clients

- docs/index.restdown
- lib/plugins/multipart_parser.js
- test/plugins.test.js
Took up where PR #694 left off to add support passing the hash option to Formidable for multipart file uploads.
> Copied fix from #694 and added test to verify

- .travis.yml
With the re-unification of Node and IOjs on the horizon, it makes sense to add iojs as a build option in the travis yaml configuration.
I've also quoted both the 0.10 and 0.12 parameters, so they showed up properly in Travis.
> Add iojs to travis config for builds

- docs/index.restdown
- lib/plugins/static.js
- test/plugins.test.js
Adds a test for @Wavewash's change in #719
Also fix up the JSCS errors.
Closes #719
> Wavewash patch 1

- .gitignore
- examples/bench/bench.js
- examples/dtrace/demo.js
- examples/dtrace/hello.js
- examples/todoapp/lib/client.js
- examples/todoapp/lib/index.js
- examples/todoapp/lib/server.js
- examples/todoapp/main.js
- examples/todoapp/test/todo.test.js
- package.json
Run `jscs examples/**/*.js` on **upstream/master**
* package.json (`deep-equal`)
* examples/todoapp/
* main.js
* lib/client.js
* test/todo.test.js
> style(examples): Unused deps, JSCS violations, gitignore

- lib/response.js
- test/formatter.test.js
**lib/response.js** contained a TODO and ESLint override related to the async formatter handler not dealing with errors being passed back. This TODO caused a warning in the lint task which led to me trying to tackle this in the lightest manner possible.
> Send 500 status if async formatter sends error

- docs/index.restdown
- lib/formatters/binary.js
- lib/formatters/json.js
- lib/formatters/jsonp.js
- lib/formatters/text.js
- lib/response.js
- test/formatter.test.js
In the past, formatters could either directly return the body if synchronous, or return a cb(err, data) if it was async.
Standardizing this interface so that all formatters must *always* return a callback instead. We also now handle the error that comes back from the formatter.
> Formatter functions now must always return a cb of the type f(err, data)

- package.json
Dtrace 0.6 has been upgraded to Nan 2 for future node support.
> Bump dtrace provider for iojs 3.x and future node support

- docs/index.restdown
Fixes #890. I also noticed that the event that fires for errors is just `InternalServer` and not `InternalServerError`, so that's been updated as well. Confirmed that the tests also listen for that event.
> Update error handling documentation

- lib/router.js
- lib/server.js
- package.json
- test/server.test.js
GH Issue #882
This PR ensures that a given route name is returned the same as specified by removing the (seemingly unnecessary) replace logic. As it stands, route names provided will be stored with any `/[^\w]/g` characters removed. This effectively makes them useless as a reference outside of the `router.render()` usage.
```js
app.get({
name: 'my-awesome-route',
path: '/my-awesome-route'
}, ...)
```
Currently provides the following `req.route` object
```js
route: { 
name: 'myawesomeroute',
path: '/my-awesome-route',
method: 'GET'
}
```
The change here proposes that the `name` property should instead be, `my-awesome-route`
> Removing replace logic for route name

- lib/plugins/audit.js
- lib/server.js
- test/server.test.js
Fixes #733.
Not sure if this is too naive, as I'm using the same place we check for `next(false)` to determine if the request should be stopped. I believe from a resource management perspective we should be okay, but would be good to get second pair of eyes on it.
> stop processing requests on which the close event has been fired

- .eslintrc
- .travis.yml
- lib/plugins/body_reader.js
Add compatibility with Node 4 for Http Status Codes
Moving between Node 0.12 and 4 introduces different http status code
messages for the request body size is too large error (413). This should
normalize between the two, picking the one that is not undefined.
Fixes #916
> Fixes GH-916 by falling back to the old HTTP 413 Error Code if not present

- test/response.test.js
Adding a test to verify behavior per #910
> should fail to set content-type header when formatter is missing

- docs/index.restdown
added more (clearer) instructions for creating HTTPS server
`fs.readFileSync` to read the files as described on https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener
> updated index.restdown

- docs/index.restdown
The documentation was using a `req` variable that is not declared. Additionally the second anonymous function definition hides the `err`, `res`, `socket`, and `head` variables.
> Fix incorrect client websocket example

- test/response.test.js
This tests if sending `null` from the response—mentioned in #941 and #942—is handled properly. I do not see the issue filed by @lukebrdn. If the error is still occurring, please provide more context, so I can try to reproduce it.
> Test sending of null body

- lib/response.js
- lib/server.js
- package.json
- test/response.test.js
- test/server.test.js
:star: :star2: :facepunch:
* Make `set` behave in a dev-friendly way whether it's called with a key-val pair or with a collection of key-val pairs
* Make `redirect` emit a `redirect` event with the `redirectLocation`
* Human-friendly assertion strings in `set`, more inline with recent assertions such as that in `redirect`
* Improve Restify install time and eventual readability by removing unused dependencies **keep-alive-agent, backoff, verror** & **tunnel-agent**
* Document that `writeHead` emits `header`
* Test that `writeHead` emits `header`
* Grammar correction for a comment
> feat(response): redirect, set & docs enhancements

- package.json
- test/server.test.js
Fixes #966, as well as the issue @jameswomack ran into when upgrading assert-plus.
Not sure how it ever worked in the first place, as assert.AssertionError is a constructor and should be called with `new`. I suspect something in core changed, since the tests run with no issue on 0.12.x.
> update dependencies, fix usage of assert.AssertionError

- lib/plugins/static.js
Hello,
just a minor fix: If you use the serveStatic plugin and have urls like:
`http://localhost/public/dir%2Ffile.jpg` or even double escaped `http://localhost/public/dir%252Ffile.jpg` restify will return an internal error with the message above.
I think adding a `%s` as first parameter is the easiest way of fixing this.
Regards,
Ben
> Fix "too few args to sprintf" for errors in static plugin

- package.json
Update restify-errors to the latest version to assert-plus lines up.
Companion to #969 
Completes the fix for #966
> Rev restify-errors so it uses the same version of assert-plus

- index.html
The wrong list item was highlighting in the sidebar when a user scrolls to the second Server API heading or clicks on the link from the sidebar. This was fixed by changing the title to a more appropriate one, Node Server API.
> Fix highlighting in sidebar by using a more specific title.

- lib/response.js
- test/response.test.js
Implements technique already being used at `/lib/upgrade.js:275` to check for the same thing. This allows for `null` and other possible edge values to be passed into `res.send()`.
> fixed #982 -- allow null to be passed to res.send()

- Makefile
- README.md
- package.json
- tools/mk/Makefile.targ
- tools/nspBadge.js
- due to npm3, cannot generate shrinkwrap for non devDeps. so we will
get vulnerabilities even in dev deps, which may be misleading.
> add nsp support

- docs/index.restdown
- lib/server.js
This change allow request handler dev to force a name for a request handler and see this name in bunyan logs instead of a meaningless "?"
> Improve request handler name handling

- docs/index.restdown
This is to  to clarify that one can pass to include request and response bodies in log output. Ref #1003
> Adding small options table to audit logger

- docs/index.restdown
This feature appears to have been removed back in 2012 —[c323034](https://github.com/restify/node-restify/commit/c323034c73308561f3d8920e0e76f333063bb0aa#diff-6d186b954a58d5bb740f73d84fe39073L155) — but the docs don't reflect that yet.
Fixes restify/node-restify#1006
> Removed doc for deprecated feature - setting default res headers

- package.json
Since restify 5.0 which integrates spdy 2.0.5 hasn't released yet, suggest updating spdy to latest 3.2.0.
> update spdy to 3.2.0

- docs/index.restdown
- Remove deprecated Request.getLogger() reference and add info to
Request.log
- Fix link in Plugins.requestLogger
fixes #1011
> Update docs for request-api

- lib/response.js
The http header fields are case sensitive according to the
RFC 2616 and 7230. This changes the 302 header field "location"
into "Location".
> Capitalize the location header field for redirect

- examples/spdy/spdy.js
It looks like this example was not updated when auditLogger was moved to restify-plugins.  These changes are enough to make the example work again, assuming the user has already installed `restify-plugins` (`npm install restify-plugins`).
> Necessary changes to make the SPDY example work

- CHANGES.md
- docs/index.restdown
- lib/index.js
- lib/server.js
- test/lib/server-withDisableUncaughtException.js
- test/response.test.js
- test/server.test.js
New server option: 'handleUncaughtExceptions' (default is false) to enable uncaughtExceptions on the server instance.
* added out-of-process tests (as now the node server instance will abort when there is an exception).
* updated some existing tests to set 'handleUncaughtExceptions' to true
> fix #1024: disable uncaughtException handler by default, added server option to enable it again

- lib/request.js
Request.absoluteUri used this.secure to determine if the protocol should be https or http, but this.secure doesn't exist anymore.
Switched to calling this.isSecure() to check if the connection is secure.
> Request.absoluteUri updated to use correct protocol.

- docs/index.restdown
The documentation is correct in so far that restify picks the highest version for a route
if no Accept-Version header is given.
However, the example shows wrong results in that it behaves the opposite way.
> Fix documentation and examples related to versioned routes

- lib/formatters/binary.js
- lib/formatters/json.js
- lib/formatters/jsonp.js
- lib/formatters/text.js
- lib/index.js
- lib/response.js
- package.json
- test/response.test.js
- test/server.test.js
Clones #1074, thanks @chb0github!
text and json formatters now do only that.
1. text/plain formatter will now invoke a toString() on the body if it exists. Otherwise the body will be empty
2. application/json formatter will attempt to find a toJson() method on the body and invoke it. If that isn't found then it will invoke JSON.stringify on the body.
> Formatters cleanup

- lib/router.js
- lib/server.js
- test/server.test.js
This removes CORS from restify core.
It also adds support for `next(false)` in pre chains. This is a prerequisite for the new [CORS plugin PR](https://github.com/restify/plugins/pull/10).
> remove CORS

- lib/router.js
- test/server.test.js
Here is the fix for #959 cherry-picked onto the 4.x branch. Please let me know if it needs and additional work -- I noticed there were a couple of `console.log` statements in this test.
> GH-959: fixes issue where cached routes were not setting maxVersion on the req

- docs/index.restdown
- lib/request.js
- lib/server.js
- package.json
- test/server.test.js
> GH-1086: reuse incoming request id headers to set request id

- lib/response.js
- test/response.test.js
This builds on top of #1025 and adds unit tests. @mramato, I hope you don't mind, I've pulled down your branch and added the unit tests. Let me know if this look ok. 
As usual, PTAL @yunong @micahr.
> GH-951: res.sendRaw() skips formatters

- docs/index.restdown
- lib/router.js
- test/router.test.js
Not sure if the idea was to have it opt-in, but that's what I've done here, since the original issue asked for an Express-like API – but I think that is the opposite of current behavior. Is that ok?
- Adds a new boolean parameter for createServer (`strict`)
- Compiles and matches paths using non-strict mode by default
Cf. #692
> Add support for strict routing

- lib/response.js
I just found out that the jsdoc is not correct for `Response.prototype.json`. My IDE notes that the function expects exactly 3 parameters what is wrong.
> JSDoc fix: net code and headers optional as they are. fixes #1113

- lib/response.js
- test/formatter.test.js
> GH-1129: always invoke res.send callback if provided

- lib/router.js
- test/router.test.js
I have a use case where I'm adding routes to the server dynamically after the server is up. I would like to be able to check if a route exists for a path before I add it, because if another route already has a similar path regex, the new route will not fire (the first route that matches the request is always the one returned from the router).
Example:
```javascript
// existing route
server.get('/users/:id', () => {});   // regex: /^\/+users\/+([^\/]*)[\/]*$/
// new route
server.get('/users/:myParamName', () => {});   // regex: /^\/+users\/+([^\/]*)[\/]*$/
```
In this case, I wouldn't want to add the new route because the existing route has the same regex even though the parameter names are different. I would like to throw an error that says a route at that path already exists on the …
> Feature: Ability to find a route by a path

- CHANGES.md
This relates to https://github.com/restify/node-restify/pull/851
https://github.com/restify/node-restify/pull/924 is the equivalent change to the changelog in the 5.x branch.
> note that this is the breaking change in 4.x

- CHANGES.md
- docs/index.restdown
- lib/plugins/query.js
- package.json
- test/plugins.test.js
- test/query.test.js
> support passing most qs options to restify.queryParser

- CHANGES.md
- docs/index.restdown
- lib/index.js
- lib/server.js
- test/lib/server-withDisableUncaughtException.js
- test/server.test.js
Back porting the server option `handleUncaughtExceptions` which allows users to disable the restify uncaughtException handler.
Note that this option is **enabled** by default in 4.x (which means no functionality change in 4.x), whereas this option will become disabled by default in 5.x - as discussed in #1024.
> backport #1024: add server option to disable the uncaughtException handler

- lib/bunyan_helper.js
- lib/request.js
- lib/server.js
- package.json
- test/server.test.js
Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …
> Update uuid to version 3.0.0

- docs/pages/components/server.md
- lib/server.js
- test/server.test.js
Emit a `close` event when server is closed.
Can be useful for middlewares that needs this information to clear up things or stop timers.
> Emit `close` event

- lib/router.js
When testify does not find a matching route it just returns an InternalServerError. However, that could be anything and it is not clear it was caused by a non-matching route.
Provide a message to the error to make it easier to find these mistakes.
> Provide explicit error message for route not found

- lib/formatters/jsonp.js
- test/formatter.test.js
http://timelessrepo.com/json-isnt-a-javascript-subset
see also:
https://golang.org/src/encoding/json/encode.go#L184
https://github.com/expressjs/express/blob/9722202df964bfbfc0f579e4baeb5a4e1b43b344/lib/response.js#L314-L317
> jsonp formatter unicode escapes line and paragraph separators

- package.json
Fixes https://github.com/restify/node-restify/issues/1305
I ran the unit tests and they still pass. I did not actually test that dtrace still works as expected with the new version, so someone will need to verify that (or show me how that should be checked).
> Update version of the dtrace-provider optionalDependency

- docs/pages/components/server.md
Updates #1290 to include:
* `|` to `or`
* Consistent capitalization
* Consistent punctuation
* `Array` -> `Array(String)` for consistency
> Bemasc create server tls docs

- README.md
Currently it looks like this, the Copyright line is in the same line with the *The MIT License (MIT)*:
> Set Copyright to it's own line

- lib/plugins/audit.js
> Node8 response headers

- package.json
dtrace-provider 0.6.0 does not work on the node 8.  This will allow restify 4.x to be compatible with node 8, rather than requiring an upgrade to restify 5.x.
> Upgrade dtrace-provider to latest

- lib/response.js
- test/response.test.js
Closes:
* Issue #1362 
Take in account opts.port passed in the object of response.redirect. If the parameter is in the object as documentation describes [Response API](http://restify.com/#response-api), then override the port.
> Port ignored in response redirect [5.X]

- lib/response.js
- test/response.test.js
Closes:
* Issue #1362 
Take in account opts.port passed in the object of response.redirect. If the parameter is in the object as documentation describes [Response API](http://restify.com/#response-api), then override the port.
> Port ignored in response redirect [4.X]

- lib/plugins/audit.js
Cloned from #1369 
Closes:
* Issue #1370 
- res._headers has been deprecated and accessing it in auditResponseSerializer generates exception (RangeError: Maximum call stack size exceeded)
- res.getHeaders returns an object that does not inherit from Object, so is unsuitable for use here
- falls back to res._headers if public APIs (introduced in v7.7.0) do not exist
see https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_headers_outgoingmessage_headernames
- see https://nodejs.org/api/http.html#http_response_getheaders
> fix(audit): use public APIs for accessing response headers

- 4TO5GUIDE.md
- docs/pages/components/response.md
- docs/pages/guides/server.md
- lib/response.js
- test/formatter.test.js
Closes:
* Issue #1347 
Async formatters were introduced as a way to handle formatting an response body by binding it to data coming from an asyncronous data source. This introduced complexities that were difficult to reconsile with the rest of the code base. By requiring all formatters to be syncronous we simplify the codebase and can :clap: **ship 5.x** :clap: 
* Removes asynchronous formatters
* Subjectively simplifies `__send` implementation
> Revert async formatters

- CHANGES.md
- lib/plugins/static.js
- package.json
- test/plugins.test.js
The 'static' plugin had a few cases where the path in a request would be
passed as the first ("message") field to a RestError constructor.
RestError uses verror.WError, which uses extsprintf to render the given
arguments. If the "message" includes "%...s" or similar printf codes,
then it will error output.
Also bump to 4.3.1.
Fixes #1382.
> fix(static): avoid user-provided data in Error messages being interpreted as sprintf codes

- docs/guides/4TO5GUIDE.md
- [ x ] Opened an issue discussing these changes before opening the PR
- [ x ] Ran the linter and tests via `make prepush`
- [ x ] Included comprehensive and convincing tests for changes
Closes:
none (conversation was part of #1400)
Migration documentation was not on the website
Moves the migration documentation down into the documentation directory so it can be used by jekyll when building the website.
> fix: Add migration guid to website

- .travis.yml
Restify is fully compatible with both node 7 and 8 and they are quite used in production also if they aren't LTS at the moment.
> Add node 7-8 travis support

- lib/response.js
- test/response.test.js
Closes:
* Issue #1408
* Issue #1407
Fully fix for Node.js v7 and v8 support. Includes the work from #1408.
Monkey patches `getHeaders` if it does not exist, and leaves it as is otherwise.
> Ianvonholt 5.x

- docs/api/plugins.md
- lib/plugins/index.js
- lib/plugins/inflightRequestThrottle.js
- test/plugins/inflightRequestThrottle.test.js
Plugin for limiting inflight requests
> Create inflightRequestThrottle plugin

- docs/api/server.md
> Fix: GH-1438, error reponse customization documentation incorrect

- lib/response.js
- test/response.test.js
Closes:
* Issue #1429
Before setting the default status code to 200 if there's been no error, it checks to see if `res.status` has been set and uses the value there if it has.
> fix: respect when status code is set with res.status (GH-1429)

- lib/plugins/audit.js
- test/plugins/audit.test.js
Closes:
* Issue #1435
Audit log timers should accumulate their value when startHandlerTimer/endHandlerTimer is called more than once for the same timer name.
Accumulates audit log timers by timer name.
> fix: audit timers of same name should accumulate (#1435)

- docs/api/server.md
- lib/response.js
- lib/server.js
- test/server.test.js
Fixes #1419 
This also removes the old FormatterError used in async formatters, which is no longer applicable.
> Fix: emit restifyError event even for router errors

- docs/api/plugins.md
Closes:
* Issue #1423 
Document undocumented options in: `bodyParser`, `jsonParser` and `multipartParser `
- Documentation: plugins
> docs(plugins): Document undocumented parser options

- test/plugins/throttle.test.js
- avoid using loopback interface IP 127.0.0.2 in the plugin/throttle tests, it doesn't work on OSX by default
> test(plugin): avoid using 127.0.0.2 in throttle tests

- .travis.yml
- lib/response.js
Fixes #1470. Exactly the same as #1407 except for 4.x.
Happy to land this and get 4.x working for node 8. Longer term, might be worth starting a discussion for EOL for 4.x. What is our level of support moving forward?
> Fix get headers 4.x

- Makefile
The current master is broken by shrinkwrap's "extraneous" issues.
TravisCI output:
```
npm ERR! Linux 4.11.6-041106-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.8.4/bin/node" "/home/travis/.nvm/versions/node/v4.8.4/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: abbrev@1.1.0 /home/travis/build/restify/node-restify/node_modules/nsp/node_modules/abbrev
```
Do not use `shrinkwrap` file to run `nsp check`.
Shrinkwrap file is only required with `--offline` flag, which is not recommended anymore, see: https://github.com/nodesecurity/nsp/blob/56f9848b6950ea821e4b92d1f1fb66ffc93bd79e/README.md#offline-mode
> Do not use shrinkwrap file to run nsp check

- .npmignore
Do not publish `.github` folder to `npm`
- Add `.github` folder to `.npmignore`.
> Do not publish .github folder to npm

- examples/dtrace/hello.js
- examples/jsonp/jsonp.js
- examples/spdy/spdy.js
Migrate spdy, dtrace and jsonp examples to the latest restify
- migrate spdy example
- migrate dtrace example
- migrate jsonp example
> Migrate spdy, dtrace and jsonp examples to the latest restify

- lib/plugins/cpuUsageThrottle.js
- test/plugins/cpuUsageThrottle.test.js
Currently, `(cpuUsageThrottle(opts).name)` returns `onRequest`. This causes `server.debugInfo` to display the wrong name for the `pre` handler. This corrects that.
> fix(cpuUsageThrottle): Correctly named handler for debugInfo

- lib/server.js
- test/server.test.js
Currently, aborting a middleware chain inside a `pre` handler will cause restify to drop the chain on the floor. This results in the `after` event not firing.
An effect of this is that `after` handlers do not get access to requests rejected by throttles.
This PR fixes that.
> fix(server): error in pre handler triggers after event

- docs/api/request.md
- test/plugins/query.test.js
Closes:
* https://github.com/restify/node-restify/issues/1502
`req.getQuery()` returns a raw query string with a `queryParser()` plugin.
- Fix `req` documentation
- Add a test for `getQuery` with `queryParser()`
> Fix docs for: req.getQuery() with queryParser()

- package.json
Update dependencies with patch and minor updates.
Escpecially `mime` that had a known security vulnerability, see:
```
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ mime                                                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ CVSS          │ 7.5 (High)                                                      │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 1.4.0                                                           │ …
```
> chore(package): update dependencies, fix security vulnerability

- .gitignore
- package-lock.json
Closes:
* https://github.com/restify/node-restify/issues/1492
* https://github.com/restify/node-restify/pull/1477
`nsp` finds vulnerabilities in the dependency tree without shrinkwrap if we have a `package-lock.json` file. 
- add `package-lock.json` file
> Add package-lock.json to improve nsp vulnerability check

- lib/plugins/audit.js
- lib/plugins/fullResponse.js
- lib/plugins/metrics.js
- lib/plugins/utils/hrTimeDurationInMs.js
- lib/server.js
- test/plugins/utilsHrTimeDurationInMs.test.js
`Date.now()` is a subject to clock drift, for performance measuring `process.hrtime()` is a better choice
- uses `process.hrtime()` for request duration meassurement
- removes unused `res._time`
> fix(plugins): use process.hrtime() for duration calculation

- lib/router.js
- test/plugins/dedupeSlashes.js
- test/router.test.js
Closes:
https://github.com/restify/node-restify/issues/1464
https://github.com/restify/node-restify/pull/1478
Non-trailing slash leads to incorrect routing match (and parameter parsing).
Fix router regexp matching with non-trailing slash(es)
> Handle non-trailing slashes correctly

- lib/plugins/cpuUsageThrottle.js
- test/plugins/cpuUsageThrottle.test.js
Currently the `lag` metric for `cpuUsageThrottle` includes the interval. For example, an interval of `50` firing at the exact right moment will result in a lag of `50` as opposed to `0`. This fixes that.
Also, this PR removes all timeouts after the `cpuUsageThrottle` tests.
> fix: dont include interval in lag

- docs/api/plugins.md
Closes:
* Issue #1395
> The documentation example is missing the the fact that `event` property of the `options` object
that needs to be passed to `restify.plugins.auditLogger(options)` is a mandatory parameter of type string.
> Update documentation for `auditLogger` plugin.
> Update auditLogger documentation

- test/plugins/audit.test.js
Fixes a flaky `audit` test.
- fix audit test
Microsecond accuracy with `process.hrtime()` can be flaky:
```
1) audit logger should log handler timers:
aTestHandler-audit-sub should be >= 1100000
+ expected - actual
-1099821
+1100000
```
```
2) audit logger should log anonymous handler timers:
handler-0 should be >= 1000000
+ expected - actual
-999662
+1000000
```
> test(audit): fix flaky test

- test/plugins/query.test.js
- test/server.test.js
Node v9.0.0 doesn't allow to call server.listen() multiple times.
(It's not clear why it was necessary earlier)
See: https://nodejs.org/api/errors.html#errors_err_server_already_listen
- remove duplicated server.listen() calls from tests
> test(server): fix ERR_SERVER_ALREADY_LISTEN issue with Node v9.0.0

- .travis.yml
- test/server.test.js
Closes:
* https://github.com/restify/node-restify/issues/1545
TravisCI trusty lacks IPv6 support and breaks with `EADDRNOTAVAIL`
- Add `TEST_SKIP_IP_V6` environment variable to skip IPv6 tests on TravisCI
> Fix broken EADDRNOTAVAIL on TravisCI

- tools/mk/Makefile.targ
Improve linting and style checking feedbacks in the makefile.
```sh
$ make prepush
Running "make check-lint"
/Users/pmarton/Documents/dev/node-restify/lib/formatters/text.js
23:5  warning  Unexpected 'todo' comment  no-warning-comments
/Users/pmarton/Documents/dev/node-restify/lib/plugins/conditionalRequest.js
109:9  warning  Unexpected 'todo' comment  no-warning-comments
/Users/pmarton/Documents/dev/node-restify/lib/server.js
866:17  warning  Unexpected 'todo' comment  no-warning-comments
/Users/pmarton/Documents/dev/node-restify/test/server.test.js
2204:21  warning  Unexpected 'todo' comment  no-warning-comments
✖ 4 problems (0 errors, 4 warnings)
Running "make check-style"
/Users/pmarton/Documents/dev/node-restify/test/server.test.js
19:32  error  Insert `;`  prettier/prettier
✖ 1 …
```
> chore(makefile): improve feedback

- README.md
Show the status of `master` branch instead of the latest build in the readme.
- replace TravisCI badge source in the README.md
> docs(readme): show master branch instead of latest build

- lib/server.js
Avoid http2 experimental warning message without http2 option
```
(node:11390) ExperimentalWarning: The http2 module is an experimental API.
```
- Only load http2 module when `http2` option is presented
> fix(server): avoid http2 experimental warning without http2 option

- lib/index.js
Docs: add createServer missing http2 option
> Docs: add createServer missing http2 option
> docs(index): add createServer missing http2 option

- docs/_api/plugins.md
- docs/_api/server.md
- lib/bunyan_helper.js
- lib/formatters/json.js
- lib/plugins/cpuUsageThrottle.js
- lib/plugins/pre/dedupeSlashes.js
- lib/plugins/pre/strictQueryParams.js
- lib/plugins/query.js
- lib/plugins/requestExpiry.js
- lib/request.js
- lib/response.js
- package.json
- tools/docsBuild.js
Update `prettier` to 1.8.1
Prettier 1.8.1 changelog:
```
Force JSON to no trailing comma in multiparser (#3182 by azz)
Don't add trailing commas in JSXAttribute for arrow functions (#3181 by duailibe)
Markdown: Allow more cases that _-style emphasis is available (#3186 by ikatyang)
Markdown: Handle additional spaces before code (#3180 by ikatyang)
Markdown: Do not break on unbreakable place (#3177 by ikatyang)
Markdown: Do not break before special prefix (#3172 by ikatyang)
```
- update `prettier` to 1.8.1
- run `make fix-style`
- run `make docs-build`
> chore(prettier): update to 1.8.1

- .gitignore
- CONTRIBUTING.md
- Makefile
- benchmark/benchmarks/response-json.js
- benchmark/benchmarks/response-text.js
- benchmark/index.js
- benchmark/lib/autocannon.js
- benchmark/lib/bench.js
- lib/response.js
- lib/server.js
- package.json
Benchmark and improve performance.
- Add benchmark suite based on https://github.com/fastify/benchmarks
- Set Content-Type to `application/json` when `res.send` is called with an Object instead of calling `res.json`
- Call `req.accepts` only once when not provided type is derived
- Eliminate some closures
- Optimize internal set header calls: use raw `res.setHeader`
Dumb servers:
```sh
$ npm start
> restify-benchmark@0.0.0 start /node-restify/benchmark
> node .
? Do you want to track progress? No
? Do you want to compare HEAD with latest release? Yes
? Do you want to run all benchmark tests? Yes
? How many connection you need? 100
? How many pipelining you need? 10
? How long does it takes? 30
---- response-json ----
✔ Results saved for head/response-json
✔ Results saved for …
```
> Performance improvement: benchmark suite and accept content-type optimization

- lib/server.js
- test/server.test.js
Earlier `server.param` didn't run with false values like an empty string.
- handle false values
- cover with tests
> Fix server.param with false values

- lib/request.js
- lib/server.js
- test/request.test.js
Closes:
* https://github.com/restify/node-restify/issues/1574
* Caused by: https://github.com/restify/node-restify/pull/1507
Fix  fix `req.time()` and `req.date()` return value.
- fix `req.time()` and `req.date()`
- cover with tests
> fix(request): date() and time() methods return value

- .travis.yml
- package.json
Drop Node.js support below `v4.0.0`.
Revisit TravisCI Node.js versions, only keep the supported releases: 
- Maintenance LTS (4.x)
- Current LTS
- Latest release
- package.json engines
- TravisCI config
> BREAKING CHANGE: dropping Node.js support < v4.0.0

- lib/plugins/jsonBodyParser.js
- test/plugins/jsonBodyParser.test.js
This is a fix for https://github.com/restify/node-restify/issues/1411 which seems to be still happening.
> fix(jsonBodyParser): fix percent sign causing server fail (#1411)

- lib/response.js
No issues opened for this.
Replaced `util.isBuffer` call with `Buffer.isBuffer`.
[`util.isBuffer`](https://nodejs.org/api/util.html#util_util_isbuffer_object) was introduced in Node 0.11 and deprecated in Node 4. [`Buffer.isBuffer`](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_isbuffer_obj) was introduced in Node 0.1 and has not been deprecated. Since Restify supports back to 0.10 according to the package.json `engines` field, `util.isBuffer` cannot be used.
> Use `Buffer.isBuffer` instead of `util.isBuffer`.

- docs/_api/plugins.md
- lib/plugins/metrics.js
Documentation improvement.
The call example for plugins.metrics didn't include the required first parameter (which itself requires a server key to be set). Compare to https://github.com/restify/node-restify/blob/master/test/plugins/metrics.test.js
Replaces https://github.com/restify/node-restify/pull/1598. Closes no issue(s).
> Update metrics plugin example

- lib/response.js
- test/response.test.js
- tools/mk/Makefile.targ
> fix: send numbers or bools as payloads

- lib/index.js
This change corrects the JSDoc annotation and removes errors from
linters and checkers like built-in into VSCode when using the
createMethod without an option object.
Thanks!
> docs: Mark options object as optional in createServer

- docs/guides/6to7guide.md
Small improvement for migration guide.
> docs(guides): add totalLatency to 6 to 7 metrics section

- lib/router.js
- lib/routerRegistryRadix.js
- test/router.test.js
- test/routerRegistryRadix.test.js
- test/server.test.js
Closes:
* Issue #1631
*This is my first pr in this project and I didn't know the rule "Opened an issue discussing these changes before opening the PR". Since I've already did all the work I hope it is ok if I open it anyway. Sorry for the inconvenience.*
Added [ignoreTrailingSlash](https://github.com/delvedor/find-my-way#api) router option.
[`find-my-way`](https://github.com/delvedor/find-my-way) does not support by default trailing slash in routes, so `/path` and `/path/` are not the same thing (and the one with the trailing slash will be a 404).
If a user need this specific behaviour it can pass `{ ignoreTrailingSlash: true }` to `find-my-way`. The result will be that internally `find-my-way` will register two …
> Added ignoreTrailingSlash router option

- docs/_api/server.md
- docs/guides/6to7guide.md
- lib/index.js
- lib/router.js
- lib/server.js
Document new option: https://github.com/restify/node-restify/pull/1632
> docs(server): document ignoreTrailingSlash

- docs/guides/6to7guide.md
Extend migration guide: path must start with `/` in 7.x
> docs(guides): path must start with / in 7.x

- docs/_api/server.md
- lib/index.js
> docs(server): update createServer JSDoc

- docs/index.md
- lib/plugins/conditionalHandler.js
- test/plugins/conditionalHandler.test.js
Fix: save `req._matchedVersion` internal for `req.matchedVersion()` in conditional handler
Closes:
https://github.com/restify/node-restify/issues/1641sue #
> fix(plugins): save req._matchedVersion

- lib/server.js
- test/server.test.js
- [ x] Opened an issue discussing these changes before opening the PR
- [ x] Ran the linter and tests via `make prepush`
- [ x] Included comprehensive and convincing tests for changes
#1348 
Closes:
* Issue #1348
* Issue #
* Issue #
Since PROXY_EVENTS are shared between every instance of a restify server, and upgrade is added but never removed, all future instances of Server will have the upgrade event proxied.
update PROXY_EVENTS to an instance variable.
> fix: proxy events into instance var and add test script

- test/plugins/jsonBodyParser.test.js
- test/plugins/static.test.js
- test/server.test.js
- test/serverHttp2.test.js
- test/upgrade.test.js
It looks like master's `make prepush` fails with a style issue. This PR fixes that and unblocks #1668
> style: fix failing check-style

- lib/server.js
- test/plugins/audit.test.js
- test/plugins/metrics.test.js
- test/server.test.js
Req close always fires in Node 10 and fires in a process.nextTick
This PR handles the close event in restify in a way that we only return an error if the response is not flushed yet.
Related changes in Node:
- https://github.com/nodejs/node/pull/20611
- https://github.com/nodejs/node/pull/20941
> fix(server): address Node v10.x req close event firing order

- docs/_api/server.md
- docs/guides/server.md
- docs/index.md
- lib/index.js
- Sync `createServer` and `Server` constructor docs
- update seever.md route versioning part
https://github.com/restify/node-restify/issues/1666
> docs(index): sync createServer and Server constructor docs

- lib/index.js
- lib/server.js
- test/server.test.js
Closes:
* Issue #1709 
The previous (prior to 7.x) functionality for uncaught exceptions only triggered the `uncaughtException` handler if it was truly an uncaught thrown error. Right now in Restify 7, if you turn on `handleUncaughtExceptions` and add a listener for the event, all errors from `next(err)` and internal errors like `MethodNotAllowed` will trigger the `uncaughtException` handler.
> Fix invalid triggers of the uncaughtException handler

- lib/server.js
- test/server.test.js
The current `uncaughtException` handler attempts to do route lookup if a string is thrown. This behavior is undesirable because it prevents the application from handling the exceptions itself (it never makes it to the user's `uncaughtException` handler.
This PR adds a check to the route lookup logic which is typically used when calling `next('myString')`. It bypasses this code if it handling an uncaught exception.
The test demonstrates how this could be triggered before these code changes: `throw 'bar'`. I also had to add a check for `err.name` since that would throw another error in the case of a string being passed to the `errEvtNameFromError` function. I made the default an empty string, but could use some feedback on whether that makes sense or not.
> [Restify 7] Fix uncaught exceptions triggering route lookups

- test/plugins/metrics.test.js
~~- [ ] Included comprehensive and convincing tests for changes~~
Is related to:
* Issue #1691
This PR makes the tests suite at `metrics.test.js` less flaky. See #1691 for more details about what is making it flaky. https://github.com/restify/node-restify/pull/1715 had fixed one of those assertions, but not all of them, which started failing once that first one was fixed.
> test: fix flaky metrics tests

- test/plugins/metrics.test.js
Closes:
* Issue #1691
Fix more occurrences of the problem described at #1691. Previous fixes did not cover the whole tests suite. I expect all it to be fully covered now.
> fix: more flaky metrics.test.js fixes

- lib/plugins/bodyReader.js
User input in `VError` based errors (`restify-errors`) can cause the process to crash as `VError` uses the `sprintf` library internally which expects additional arguments for formatting symbols liek `%s`.
For example, a `content-type` `%s` would crash restify without this change.
> fix(plugins): do not include user-input in UnsupportedMediaTypeError

- lib/server.js
Closes:
* Issue #1731
Restify currently relies on specific timing of the response's 'close' event to emit the 'after' event with the correct error parameter in case the request is aborted by the client.
This PR makes Restify _not_ overwrite any error previously set as `res.err` so that it is passed as the first parameter when emitting the `'after'` event once the req/res lifecycle is finished.
> fix: emit after event with proper error param for node versions >= 11.4.0

- docs/_api/plugins.md
- docs/_api/server.md
- lib/plugins/pre/context.js
- test/plugins/context.test.js
- test/plugins/plugins.test.js
Add req.get() which returns the whole context
> feat(plugins): context, req.get() returns the whole context

- docs/index.md
Closes:
* Issue #
* Issue #
* Issue #
This updates a documentation bug. `restify.plugins.dedupeSlashes()` does not exist, but `restify.plugins.pre.dedupeSlashes()` does.
> update dedupeSlashes() invocation in docs

- docs/_api/request.md
- docs/api/request-events.md
- docs/config/request.yaml
- lib/server.js
- test/request.test.js
Emit a `restifyDone` event on the `req` object when the request is "fully served" (see docs in this PR).
> feat(req): add restifyDone event

- .travis.yml
- README.md
- package.json
- test/plugins/jsonBodyParser.test.js
- test/plugins/static.test.js
- test/serverHttp2.test.js
- test/upgrade.test.js
Closes: None
* Issue #
* Issue #
* Issue #
This PR is to upgrade `find-my-way` to  `^2.0.0` which drops support for Node 4.x. This means going forth restify will also drop support for Node 4.x. The changes included in this PR also upgrades `lodash@4.17.11` (4.17.10 had a vulnerability) and marks target engine as Node 6.x or above. Some of the test files were changed by `make fix-style`.
> breaking: restify drops Node v4.x and v6.x

- CHANGELOG.md
Update changelog to reflect the fact that restify dropped support for Node 4.x and 6.x
Closes:
* Issue #
* Issue #
* Issue #
Updates changelog to clearly state that restify dropped support for Node 4.x and 6.x
> docs(CHANGELOG): Update changelog

- lib/router.js
- test/router.test.js
Closes:
* Issue #1684 
* Issue #
* Issue #
* Adds `render()` to `router.js`
* Adds unit tests
This PR fixes #1684 and brings back the `router.render()`. Most of the work was done in PR #1702 just added some documentation and cleaned up tests a little bit.
> feat: add router.render() back to support hypermedia usecase

- lib/server.js
- test/server.test.js
Restify doesn't properly handle non-errors being thrown inside the domain. The two tests augmented in this PR are currently passing unintentionally. When you dump the response sent back from restify, they actually show restify blowing up while attempting to handle the domain, and not the original non-error value thrown in the domain: `TypeError: Cannot read property \'statusCode\' of undefined` and `AssertionError [ERR_ASSERTION]: first argument to VError, SError, or WError constructor must be a string, object, or Error (string) is required'`. 
I think this behavior is unintentional. @misterdjules I'm not sure if this is related to your previous domain findings, but it appears the domain is able to re-catch the secondary exception thrown by restify code attempting to handle the original …
> fix: properly handle non-errors thrown in domains

- package.json
This fixes `make benchmark`.
Upgrades autocannon-compare. Autocannon is actually on 3.x now, which we might want to look into. We might have to do some work though since autocannon-compare [does not yet support 3.x format](https://github.com/mcollina/autocannon-compare/pull/1).
> upgrade: autocannon-compare@0.4.0

- lib/plugins/cpuUsageThrottle.js
- test/plugins/cpuUsageThrottle.test.js
A commit semver major upgraded the `pidusage` module.
https://github.com/restify/node-restify/pull/1755/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R109
The cpuUsageThrottle tests `proxyquire`d out the entire module, preventing them from failing even though the module changed it's API.
https://github.com/restify/node-restify/blob/e4007cf69053c12d3c2919db96a0f5d0a0358310/test/plugins/cpuUsageThrottle.test.js#L12-L18
This PR:
* Updates the plugin to use the new API for the `pidusage` module
* Adds a test which validates the API for the `pidusage` module
> fix(cpuUsageThrottle): support breaking change in pidusage module

- docs/api/server-events.md
- lib/server.js
- test/server.test.js
Closes:
* Issue https://github.com/restify/node-restify/issues/1765
The 'after' event is not called when a request has an uncaught exception (using `handleUncaughtExceptions`) if the request has been aborted before the exception.
This PR is a proposal for a mechanism to fix the issue by adding a continuation function to the `uncaughtException` handler.  If this continuation function isn't called, then restify can never know that a request has completed all work and call the 'after' handler (because `aborted` is triggered on the request object before work has completed, so neither `finish` nor `close` ever get triggered on the response and thus we have no other signal that work has completed).  This is actually …
> feat: provide callback to uncaughtException handler

- Makefile
- test/server.test.js
- test/upgrade.test.js
- tools/mk/Makefile.targ
Two issues. 
1) Upgrade tests are failing locally (and likely on CI), but we didn't know about it. Travis isn't running all of the nodeunit tests for some reason (??). We need to investigate.
2) Something has changed in recent Node 10 release, perhaps a lifecycle ordering change or something else like we saw previously. The upgrade test is currently set up in a way that requires proper response lifecycle cleanup to exit properly. This doesn't seem to be happening, as calling `res.resume()` on an upgraded request isn't triggering the correct behavior to allow the server to "close/resume" the response from restify, which leaves the client hanging. 
I updated the test to exit the test earlier and not depend on proper response cleanup, as I suspect in the field we wouldn't really want to be …
> fix(test): make upgrade test pass

- test/plugins/cpuUsageThrottle.test.js
Tests were hanging for 30sec after the runner had completed. Looks like the `pidusage` defaults to a 30s interval so it was waiting for that before the test runner could exit. 
Removes the pidusage handler from the test once complete.
> chore(tests): clear event loop to end tests faster

- .npmignore
This lightens up the bundle by roughly `43.2Mb`
Closes:
* Issue #1778 
> Excludes the `becnhmark` folder from the final npm bundle.
> Removes the benchmark folder from the npm package

- lib/chain.js
- test/chain.test.js
Schedule handlers to nextTick for cleaner Flamegraphs.
Shouldn't have an effect on performance:
```
? Do you want to track progress? No
? Do you want to compare HEAD with the stable release (7.2.0)? Yes
? Do you want to run all benchmark tests? Yes
? How many connections do you need? 100
? How many pipelining do you need? 10
? How long does it take? 30
---- response-json ----
⠋ Started head/response-json
✔ Results saved for head/response-json
✔ Results saved for stable/response-json
response-json throughput:
{
"significant": "",
"equal": true
}
---- response-text ----
✔ Results saved for head/response-text
✔ Results saved for stable/response-text
response-text throughput:
{
"significant": "",
"equal": true
}
---- router-heavy ----
✔ Results saved for head/router-heavy
✔ Results saved for …
```
> feat(chain): schedule handlers to the next tick

- lib/formatters/json.js
- lib/response.js
- package.json
- test/formatter.test.js
Summary: Don't always blowup (uncaughtException) when we can avoid it, like in scenarios where a JSON payload does not properly parse or serialize.
Details:
When a formatter throws an error that is an instanceof restify-errors' `HttpError` or `RestError`, handle it gracefully by catching & passing to `formatterErrors`.
> Gracefully handle formatters throwing restify errors.

- lib/chain.js
- test/request.test.js
- test/server.test.js
BREAKING CHANGE: Using setImmediate has more overhead than nextTick on
Node.js v12. Benchmarks show improvements of >20% when changing
setImmediate to nextTick:
```
response-json throughput:
{
"significant": "***",
"equal": false,
"wins": "head",
"diff": "28.62%"
}
---- response-text ----
✔ Results saved for head/response-text
✔ Results saved for stable/response-text
response-text throughput:
{
"significant": "***",
"equal": false,
"wins": "head",
"diff": "43.45%"
}
---- router-heavy ----
✔ Results saved for head/router-heavy
✔ Results saved for stable/router-heavy
router-heavy throughput:
{
"significant": "***",
"equal": false,
"wins": "head",
"diff": "30.02%"
}
---- middleware ----
✔ Results saved for head/middleware
✔ Results saved for stable/middleware
middleware throughput:
{ …
```
> feat(chain): use nextTick instead of setImmediate

- benchmark/package.json
`*` will match any stable release, which means if there's already a
restify version installed in the benchmarks directory, npm won't try to
update it. `latest` only matches the latest version, which means npm
will always update to the latest stable version (unless it's already
installed). This behavior can be checked with https://semver.npmjs.com/.
> fix(benchmark): force latest restify version

- lib/server.js
- package.json
```
$ node -v
v12.13.1
$ make benchmark 
? Do you want to track progress? No
? Do you want to compare HEAD with the stable release (7.2.0)? Yes
? Do you want to run all benchmark tests? Yes
? How many connections do you need? 100
? How many pipelining do you need? 10
? How long does it take? 30
---- response-json ----
✔ Results saved for head/response-json
✔ Results saved for stable/response-json
response-json throughput:
{
"significant": "***",
"equal": false,
"wins": "head",
"diff": "235.59%"
}
---- response-text ----
✔ Results saved for head/response-text
✔ Results saved for stable/response-text
response-text throughput:
{
"significant": "***",
"equal": false,
"wins": "head",
"diff": "204.37%"
}
---- router-heavy ----
✔ Results saved for head/router-heavy
✔ Results saved for …
```
> fix(server): address domain performance regression with Node v12.x

- docs/index.md
Closes:
* Issue #1804 
Changes `#error%20handling` to the correct id `#error-handling` in the link.
> Fix the link for Error Handling section in docs

- docs/index.md
The restify.errors object was removed long ago but still used here.
This seems to cause some confusion to users that copy paste the code to try it.
Closes:
* Issue #1830 (partially)
* Issue #1806 
Remove `restify.errors` from a couple of examples.
> docs(index): Remove restify.errors from examples

- .github/workflows/release-please.yml
Maintainance: use GitHub actions instead of relying on manually using `unleash`.
It uses GCP's release-please-action to generate an automated release PR with CHANGELOG and automated version bumping.
> chore: use release-please-action

- .github/workflows/ci.yml
- test/plugins/audit.test.js
improves integration with Github Actions.
Maintainance PR. Will remove Travis on subsequent PR if Github CI meets the expectation.
> chore: use github ci

- lib/server.js
- test/server.test.js
Closes:
* Issue #1774 
If we reach the end of a handler chain and the headers haven't been sent yet, send a 500 back to the client.
> feat: send 500s for unhandled requests

- .eslintrc.js
- .travis.yml
- docs/guides/8to9guide.md
- lib/chain.js
- lib/errorTypes.js
- lib/server.js
- package.json
- test/chain.test.js
- test/lib/helper.js
- test/plugins/inflightRequestThrottle.test.js
- test/server.test.js
_This PR has two **commits**:_
1. drops support to node 8.x (EOL);
2. adds support for async/await functions on `pre`, `use` and route handlers;
**_Example of async handling:_**
```js
const restify = require('restify');
const server = restify.createServer();
server.pre(async function (req, res) {
await something();
doSomethingElse();
});
server.get('/async', async function (req, res) {
const body = await thatThing();
res.send(body);
});
```
Basically, the `Chain` call will check if the handler return is a `Promise` (by checking the existence of `.then`, as Falcor Router does it) and resolves by calling `next` or rejects by calling `next with error`.
.
> 9.X - async/await

- lib/chain.js
- lib/server.js
- test/server.test.js
**BREAKING CHANGE**: deprecates and removes re-routing when passing a `string` parameter to `next()`
* Issue #1845
Assumes the standard node.js callback API: `cb(err, value)` and treats `next()` as a callback. This way:
1. deprecates and removes re-routing;
2. `next('foo')` will be considered an error;
3. the returned value from an async function is ignored (as it would for `next(null, 'foo')`);
> feat: remove re-routing from handler

- lib/response.js
The jsdoc now matches the required/supported types, as checked by the assertion in the function body.
> fix jsdoc for response.sendRaw

- .github/workflows/ci.yml
- lib/plugins/bodyReader.js
- test/plugins/static.test.js
The close event from the request object is not guaranteed to fire on the
same order across major versions of Node.js, the more accurate way to
look if the connection was closed is to listen to the event on the
socket. Fixes tests on v16.
Ref: https://github.com/nodejs/node/issues/38924
> fix: use more reliable close event

- docs/_api/server.md
- lib/index.js
- lib/server.js
There are a few lines in docs for `handleUncaughtExceptions` option,
both in markdown docs and in jsdoc, which seem irrelevant and
disconnected. This appears to be a mistake that has been copied to
several places.
> docs: fix handleUncaughtExceptions docs typos

- lib/plugins/bodyReader.js
- test/plugins/bodyReader.test.js
In #1880, we switched from using the close event on `req` to close on
`req.socket`. This addressed the intended issue but can trigger frequent
warnings when keep-alive is used due to a listener being added for each
request on the same socket.
By using the close event on `res` instead, we address both the issue of
event ordering in Node.js >= 16 that the original change was targeting
and the event emitter warning leak.
Fixes #1883.
> fix: use close event on response instead of socket

- lib/server.js
- test/server.test.js
Closes:
* Issue #1894
- NOT create empty `clientError` listener for `http.Server`.
> fix: don't create empty clientError listener for http.Server

- lib/server.js
- test/server.test.js
In the recent fix #1895, the `clientError` event was removed from the
list of events proxied from the underlying server object to the restify
Server. That fix was needed because merely adding a listener to the
underlying server for the `clientError` event prevents the default
behavior of returning an appropriate error code and closing the socket.
So by setting up a listener to proxy the event we were preventing that
default behavior, leading to hanging/leaked requests.
But! We should still support proxying `clientError` events if restify
users have added a listener for it. This enables logging or other custom
behavior. Restify users adding a `clientError` listener take on the
responsibility of sending an appropriate error and closing the socket,
exactly as noted in the Node.js docs for …
> fix: Re-add support for clientError listeners

- lib/chain.js
- lib/router.js
- test/chain.test.js
The error that is bubbled up when using a handler with the wrong number
of arguments was an unintelligible assertion error with no info about
what failed. This made it nearly impossible to find the problem.
This change adds a better error message including contextual info so
that this error is actionable.
Closes #1898
> fix: make arity error message actionable

- package.json
- [ x ] Opened an issue discussing these changes before opening the PR
- [ x ] Ran the linter and tests via `make prepush`
- [ n/a ] Included comprehensive and convincing tests for changes
- Helps address vulnerability in serenity-js as part of [issue #1062](https://github.com/serenity-js/serenity-js/issues/1062#issuecomment-989428443)
- bumps version of http-signature to ^1.3.6
> chore: bump version of http-signature to ^1.3.6

- .github/workflows/ci.yml
- README.md
- lib/chain.js
- lib/plugins/static.js
- lib/request.js
- test/chain.test.js
- test/chainComposer.test.js
- test/request.test.js
- test/router.test.js
Node.js added `closed` getter-only property to streams. This commit deprecates req.closed to avoid monkey-patching something that might be used in Node.js core or user-land libraries.
`req.connectionState() === 'close'` can be used to achieve the same result moving forward. req.closed will be removed on Restify 10 to open way to support Node.js v18.
Closes:
* Issue #
* Issue #
* Issue #
> feat: deprecate req.closed

- package.json
- test/router.test.js
- test/routerRegistryRadix.test.js
Closes:
https://github.com/restify/node-restify/issues/1811, https://github.com/restify/node-restify/issues/1873 and https://github.com/restify/node-restify/issues/1874
* closes #1900
* closes #1868
* potentially closes issue #1811
* potentially closes issue #1873
* potentially closes issue #1874
* Upgrades `find-my-way` routing library to latest ^7.2.0.
* Updates the `toString()` tests on routes to match new output.
> chore: bump find-my-way to ^7.2.0

- examples/http2/http2.js
When following the example, many connections don't work. e.g. curl returned:
>Unknown ALPN Protocol, expected `h2` to be available.
>If this is a HTTP request: The server was not configured with the `allowHTTP1` option or a listener for the `unknownProtocol` event.
Allows automatic downgrade to http1. Node's http2 module allows https or http2 with the same code.
> Update example to allow downgrading to http1

- .github/workflows/ci.yml
- lib/request.js
- lib/server.js
- test/request.test.js
* Remove `closed()` monkey-patch, rely on connectionState instead (GH-1888)
* fix IPv6 url by supporting new server.address().family format
* add node 18 to GH Actions
Co-authored-by: mary marchini <oss@mmarchini.me>
Closes:
* Issue #
* Issue #
* Issue #
> fix: support v18.x

- lib/plugins/audit.js
- lib/server.js
- test/plugins/audit.test.js
- test/server.test.js
So it's consistent with other plugins, and to allow child loggers
attached to req to be used on audit.
Closes:
* Issue #
* Issue #
* Issue #
> feat!: use req.log on audit plugin

- lib/server.js
- test/server.test.js
domains is deprecated, but there isn't a standard alternative in the ecosystem as of right now. Instead of implementing a bespoke alternative to it, let users create their own alternatives (or use libraries) by providing a generic way to replace domains in the error handling workflow. Note: unless you know what you're doing, you should NOT be using this feature.
> feat: allow custom alternatives to domains

- lib/server.js
First of all, thanks for the great Restify!! 
I've been using it for years in several projects (including [this](https://github.com/nttgin/BGPalerter)).
- [x ] Opened an issue discussing these changes before opening the PR
- [x ] Ran the linter and tests via `make prepush`
- [x ] Included comprehensive and convincing tests for changes (same coverage)
Closes:
* Issue #1876
Support for Node14 will end in 2 months, we need to move to Node 16+.
However, restify imports spdy, which raises 
```
DeprecationWarning: Access to process.binding('http_parser') is deprecated.
```
The good news is that most of the time spdy is not used since you need to pass `options.spdy`.
We can simply avoid deprecation warnings (and also avoid to run unused code) by importing spdy on request (as currently done for …
> avoid loading spdy if not used and prevent deprecation warning

- lib/plugins/audit.js
- lib/plugins/requestLogger.js
- test/plugins/audit.test.js
- test/plugins/plugins.test.js
Right now the child loggers add the request id attribute under the field name `req_id`. This change adds an option to override the field name.
This allows more customizable logs for easier integration with backend logging frameworks.
> feat: allow alternate name for request id in logs

- .github/workflows/ci.yml
- test/server.test.js
Closes:
* Issue #
* Issue #
* Issue #
> feat: support Node.js 20
